version: '3.4'

services:
  qolabdb:
    container_name: qolabdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=QolabDB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/posgresql/data

  qolab.api:
    container_name: qolab.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionSting=Server=qolabdb;Port=5432;Database=QolabDb;User Id=admin;Password=admin1234;"
    depends_on:
      - qolabdb
    ports:
      - "8000:80"
